name: "nix"
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
jobs:
  update-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 1
      - name: "git: setup"
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - uses: cachix/install-nix-action@v20
      - name: "flake: update inputs"
        run: nix flake update --commit-lock-file
      - name: "flake: check eval"
        run: nix flake check
      - name: "git: push changes"
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}

