  name: Update Nix Flake Lock
  # You may pin to the exact commit or the version.
  # uses: DeterminateSystems/update-flake-lock@a3ccb8f59719c48d6423e97744560221bcf7a3fa
  uses: DeterminateSystems/update-flake-lock@v21
  with:
    # A space-separated list of inputs to update. Leave empty to update all inputs.
    inputs: # optional, default is 
    # GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)
    token: # optional, default is ${{ github.token }}
    # The message provided with the commit
    commit-msg: # optional, default is flake.lock: Update
    # Sets the pull request base branch. Defaults to the branch checked out in the workflow.
    base: # optional
    # The branch of the PR to be created
    branch: # optional, default is update_flake_lock_action
    # The path of the directory containing `flake.nix` file within your repository. Useful when `flake.nix` cannot reside at the root of your repository.
    path-to-flake-dir: # optional, default is 
    # The title of the PR to be created
    pr-title: # optional, default is flake.lock: Update
    # The body of the PR to be created
    pr-body: # optional, default is Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.

```
{{ env.GIT_COMMIT_MESSAGE }}
```

### Running GitHub Actions on this PR

GitHub Actions will not run workflows on pull requests which are opened by a GitHub Action.

To run GitHub Actions workflows on this PR, run:

```sh
git branch -D update_flake_lock_action
git fetch origin
git checkout update_flake_lock_action
git commit --amend --no-edit
git push origin update_flake_lock_action --force
```

    # A comma or newline separated list of labels to set on the Pull Request to be created
    pr-labels: # optional, default is 
    # A comma or newline separated list of assignees (GitHub usernames).
    pr-assignees: # optional, default is 
    # A comma or newline separated list of reviewers (GitHub usernames) to request a review from.
    pr-reviewers: # optional, default is 
    # Author name used for commit. Only used if sign-commits is false.
    git-author-name: # optional, default is github-actions[bot]
    # Author email used for commit. Only used if sign-commits is false.
    git-author-email: # optional, default is github-actions[bot]@users.noreply.github.com
    # Committer name used for commit. Only used if sign-commits is false.
    git-committer-name: # optional, default is github-actions[bot]
    # Committer email used for commit. Only used if sign-commits is false.
    git-committer-email: # optional, default is github-actions[bot]@users.noreply.github.com
    # Set to true if the action should sign the commit with GPG
    sign-commits: # optional, default is false
    # GPG Private Key with which to sign the commits in the PR to be created
    gpg-private-key: # optional, default is 
    # Fingerprint of specific GPG subkey to use
    gpg-fingerprint: # optional
    # GPG Private Key Passphrase for the GPG Private Key with which to sign the commits in the PR to be created
    gpg-passphrase: # optional, default is 
    # A space-separated list of options to pass to the nix command
    nix-options: # optional, default is 
          
